
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smallshop?autoReconnect=true&useSSL=false
    username: root
    password: hooman2731
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true





